name: hAntiBuildSourceCodeLeak
main: net.vizexmc.AntiBuild.AntiBuildSourceCodeLeak
author: HapeDev / BukkitHelpSourceCodeLeak
version: 1.1SourceCodeLeak

commands:
  antibuild:
    description: De-/Aktiviert das Bauen! SourceCodeLeak